### ISSUE TITLE
Default value never fetched in Twig Extension

### ISSUE THREAD

**Issue by TonySma** [monsieurbiz/SyliusSettingsPlugin#37]
There is a bug here, if no save action is performed in admin before using this function, then the result will be always null. 
https://github.com/monsieurbiz/SyliusSettingsPlugin/blob/master/src/Twig/Extension/SettingsExtension.php#L79

The default value in the config file must be used if present. 

I will open a PR for this soon.

**Comment by jacquesbh** [comment]
Hi @TonySma !

Do you still have this issue?

Thanks!
