### ISSUE TITLE
is it possible to use entitytype

### ISSUE THREAD

**Issue by t-n-y** [monsieurbiz/SyliusSettingsPlugin#70]
Is it possible to use an entityType, to set a collection of other entity in the configuration ?

I am looking a way to do that but can't find any exemple

**Comment by delyriand** [comment]
Hi @t-n-y,

Yes, it's possible to use the `EntityType::class` in your form type. 
You just need to define a [data transformer](https://symfony.com/doc/current/form/data_transformers.html).

Example with a "Page" entity from another [beautiful plugin](https://github.com/monsieurbiz/SyliusCmsPagePlugin):

```php
$this->addWithDefaultCheckbox(
    $builder, 'page', EntityType::class, [
        'class' => Page::class,
        'choice_label' => 'title',
       // ...
    ]
);

$pageToCodeTransformer = new ReversedTransformer(new ResourceToIdentifierTransformer($this->pageRepository, 'code'));
$builder->get('page')->addModelTransformer($pageToCodeTransformer);
```

**Comment by t-n-y** [comment]
Hi @delyriand,

Thank you for the quick response. 
I'll try to implement that. So if i understand well, you re finally saving the code string in the text_value field ?

**Comment by delyriand** [comment]
@t-n-y, That's right!
