### ISSUE TITLE
Add Sylius 1.13 compatibility

### ISSUE THREAD

**Issue by danakil** [monsieurbiz/SyliusSettingsPlugin#71]
Hello,
This plugin don't supports Sylius 1.13. Is there anything preventing to loosen this constraint ?
Thank you for your work

**Comment by maximehuran** [comment]
Hi danakil,

The support of 1.13 version will arrive soon as we can.
Feel free to contribute if you want to help us doing it ☺️

Example for the 1.12 upgrade : https://github.com/monsieurbiz/SyliusSettingsPlugin/pull/55

**Comment by danakil** [comment]
> The support of 1.13 version will arrive soon as we can. Feel free to contribute if you want to help us doing it ☺️

Unfortunaly, I don't even have the time to do my own work at the moment, that's why I was looking at your plugin to ease my pain a little bit :) I didn't want to rush you, and thank you for your work !

**Comment by maximehuran** [comment]
Stay tuned we will try to release as soon as we can ;)

**Comment by danakil** [comment]
Many thanks !
